{% set version = "0.1.1" %}

package:
  name: jupyterlab-webrtc-docprovider
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/j/jupyterlab-webrtc-docprovider/jupyterlab-webrtc-docprovider-{{ version }}.tar.gz
  sha256: a1578d88ed8e46c0b74af39df364eb73be60d494ab5ff7bad486c0ef9c04b668

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 1

requirements:
  host:
    - jupyter-packaging >=0.10,<1.0
    - pip
    - python {{ python_min }}
  run:
    - python >={{ python_min }}

test:
  imports:
    - jupyterlab_webrtc_docprovider
  commands:
    - pip check
    - jupyter labextension list
    - jupyter labextension list 1>labextensions 2>&1
    - cat labextensions | grep -ie "@jupyterlite/webrtc-docprovider .*OK"  # [unix]
    - pytest -vv --pyargs jupyterlab_webrtc_docprovider --cov=jupyterlab_webrtc_docprovider --cov-fail-under=100 --cov-report=term-missing:skip-covered
  requires:
    - pip
    - pytest-cov
    - jupyterlab >=3.1,<4
    - python {{ python_min }}

about:
  home: https://github.com/jupyterlite/jupyterlab-webrtc-docprovider
  summary: Document collaboration for JupyterLab and JupyterLite, powered by y-webrtc
  license: BSD-3-Clause
  license_file:
    - LICENSE
    - jupyterlab_webrtc_docprovider/labextension/static/third-party-licenses.json

extra:
  recipe-maintainers:
    - bollwyvl
